### ISSUE TITLE
airprobe - swig error: Unrecognized option -pthread

### ISSUE THREAD

**Issue by ghost** [pcabreracamara/airprobe#1]
I constantly get this error, put on a clean operating system, libosmocore last version
Ubuntu 16.04 64bit
gnuradio 3.7.9

~ / data / airprobe / gsm-receiver $ make
............................................
/ bin / rm -f .deps / gsm.Std; \
.deps / gsm.Sd .deps / gsm.Std; \
    fi \
else \
    / bin / rm -f .deps / gsm.S *; exit 1; \
fi
swig error: Unrecognized option -pthread
Use 'swig -help' for available options.
Makefile: 1217: recipe for target '.deps / gsm-generate-stamp' failed
make [5]: *** [.deps / gsm-generate-stamp] Error 1
make [5]: Leaving directory '/ home / vic / data / airprobe / gsm-receiver / src / lib'
/ bin / bash ../../libtool --tag = CXX --mode = compile g ++ -DHAVE_CONFIG_H -I. -I ../ .. -I -I -I / usr / include -I / usr / include / gnuradio / swig -pthread -I / usr / local / include / -I ../../ src / lib / decoder / openbtsstuff -I / usr / include / python2.7 -g -O1 -Wno-strict-aliasing -Wno-parentheses -g -O2 -Wall -Woverloaded-virtual -MT _gsm_la-gsm.lo -MD -MP -MF .deps / _gsm_la-gsm.Tpo -c -o _gsm_la-gsm.lo `test -f 'gsm.cc' || echo './'`gsm.cc
libtool: compile: g ++ -DHAVE_CONFIG_H -I. -I ../ .. -I -I -I / usr / include -I / usr / include / gnuradio / swig -pthread -I / usr / local / include / -I ../../ src / lib / decoder / openbtsstuff -I / usr / include / python2.7 -g -O1 -Wno-strict-aliasing -Wno-parentheses -g -O2 -Wall -Woverloaded-virtual -MT _gsm_la-gsm.lo -MD -MP -MF .deps / _gsm_la-gsm.Tpo -c ./gsm.cc -fPIC -DPIC -o .libs / _gsm_la-gsm.o
g ++: error: ./gsm.cc: No such file or directory
g ++: fatal error: no input files
compilation terminated.

**Comment by pcabreracamara** [comment]
Hi Victor,

That's and OS problem; your g++ compiler can't find `gsm.cc` in `/home/vic/data/airprobe/gsm-receiver/src/lib` folder. Check the `CPPFLAFS` and `CXXFLAGS` variables:

> @am__fastdepCXX_FALSE@	$(AM_V_CXX@am__nodep@)$(LIBTOOL) $(AM_V_lt) --tag=CXX $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(_gsm_la_CXXFLAGS) $(CXXFLAGS) -c -o _gsm_la-gsm.lo `test -f 'gsm.cc' || echo '$(srcdir)/'`gsm.cc

Review the environment variables to avoid the problem or you can just execute by hand the libtool command in `/home/vic/data/airprobe/gsm-receiver/src/lib` folder in order to check what's going on and correct the problem by hand if you are not familiar with Linux make environment:

`libtool --tag=CXX --mode=compile g++ -DHAVE_CONFIG_H -I. -I ../ .. -I -I -I /usr/include -I /usr/include/gnuradio/swig -pthread -I /usr/local/include/ -I ../../src/lib/decoder/openbtsstuff -I /usr/include/python2.7 -g -O1 -Wno-strict-aliasing -Wno-parentheses -g -O2 -Wall -Woverloaded-virtual -MT _gsm_la-gsm.lo -MD -MP -MF .deps/_gsm_la-gsm.Tpo -c -o _gsm_la-gsm.lo `test -f 'gsm.cc'` || echo './'gsm.cc`

(**Important:** copy and paste that code from your terminal, as here some special characters are missing). Once you've generate by hand the `gsm.cc` file, you can continue the whole compilation process with the make command.

Cheers,
Pedro

**Comment by ghost** [comment]
1. Installed a clean UBUNTU 16.04 64 bit

2. installed libosmocore

3.sudo apt install gnu radio 3.7.9

4. installed gr-gsm

5.git clone https://github.com/velichkov/gr-gsm.git

6 vic @ vic: ~ / airprobe / gsm-receiver $ make
(https://github.com/iamckn/airprobe)

  Mistake:
swig error: Unrecognized option -pthread
Use 'swig -help' for available options.
Makefile: 1217: recipe for target '.deps / gsm-generate-stamp' failed
make [5]: *** [.deps / gsm-generate-stamp] Error 1
make [5]: Leaving directory '/ home / vic / airprobe / gsm-receiver / src / lib'
/ bin / bash ../../libtool --tag = CXX --mode = compile g ++ -DHAVE_CONFIG_H -I. -I ../ .. -I -I -I / usr / include -I / usr / include / gnuradio / swig -pthread -I / usr / local / include / -I ../../ src / lib / decoder / openbtsstuff -I / usr / include / python2.7 -g -O1 -Wno-strict-aliasing -Wno-parentheses -g -O2 -Wall -Woverloaded-virtual -MT _gsm_la-gsm.lo -MD -MP -MF .deps / _gsm_la-gsm.Tpo -c -o _gsm_la-gsm.lo `test -f 'gsm.cc' || echo './'`gsm.cc
libtool: compile: g ++ -DHAVE_CONFIG_H -I. -I ../ .. -I -I -I / usr / include -I / usr / include / gnuradio / swig -pthread -I / usr / local / include / -I ../../ src / lib / decoder / openbtsstuff -I / usr / include / python2.7 -g -O1 -Wno-strict-aliasing -Wno-parentheses -g -O2 -Wall -Woverloaded-virtual -MT _gsm_la-gsm.lo -MD -MP -MF .deps / _gsm_la-gsm.Tpo -c ./gsm.cc -fPIC -DPIC -o .libs / _gsm_la-gsm.o
g ++: error: ./gsm.cc: No such file or directory
g ++: fatal error: no input files
compilation terminated.
Makefile: 750: recipe for target '_gsm_la-gsm.lo' failed
make [4]: ​​*** [_gsm_la-gsm.lo] Error 1
make [4]: ​​Leaving directory '/ home / vic / airprobe / gsm-receiver / src / lib'
Makefile: 880: recipe for target 'all-recursive' failed
make [3]: *** [all-recursive] Error 1
make [3]: Leaving directory '/ home / vic / airprobe / gsm-receiver / src / lib'
Makefile: 421: recipe for target 'all-recursive' failed
make [2]: *** [all-recursive] Error 1
make [2]: Leaving directory '/ home / vic / airprobe / gsm-receiver / src'
Makefile: 576: recipe for target 'all-recursive' failed
make [1]: *** [all-recursive] Error 1
make [1]: Leaving directory '/ home / vic / airprobe / gsm-receiver'
Makefile: 484: recipe for target 'all' failed
make: *** [all] Error 2
vic @ vic: ~ / airprobe / gsm-receiver $


7. vic @ vic: ~ / airprobe / gsm-receiver / src / lib $ libtool --tag = CXX --mode = compile g ++ -DHAVE_CONFIG_H -I. -I ../ .. -I -I -I / usr / include -I / usr / include / gnuradio / swig -pthread -I / usr / local / include / -I ../../src/lib/ decoder / openbtsstuff -I /usr/include/python2.7 -g -O1 -Wno-strict-aliasing -Wno-parentheses -g -O2 -Wall -Woverloaded-virtual -MT _gsm_la-gsm.lo -MD -MP -MF .deps / _gsm_la-gsm.Tpo -c -o _gsm_la-gsm.lo test -f 'gsm.cc' || echo './'gsm.cc
libtool: compile: g ++ -DHAVE_CONFIG_H -I. -I ../ .. -I -I -I / usr / include -I / usr / include / gnuradio / swig -pthread -I / usr / local / include / -I ../../src/lib/ decoder / openbtsstuff -I /usr/include/python2.7 -g -O1 -Wno-strict-aliasing -Wno-parentheses -g -O2 -Wall -Woverloaded-virtual -MT _gsm_la-gsm.lo -MD -MP -MF .deps / _gsm_la-gsm.Tpo -c test -f gsm.cc -fPIC -DPIC -o .libs / _gsm_la-gsm.o
g ++: error: test: No such file or directory
g ++: error: gsm.cc: No such file or directory
g ++: error: unrecognized command line option
./gsm.cc
vic @ vic: ~ / airprobe / gsm-receiver / src / lib $

The error remained if I did everything right. I am not a programmer. I can’t solve this problem for about two months, I searched the network for solutions periodically. Many have such an error. I somehow managed to install the airprobe package on UBUNTU 16.04 36 bit three times. Now to use go.sh I am converting a file on another computer with 32 bit. But under 32bit Kraken does not work. As I understand it on 64 bit, is that so? But lately, airprobe is not set to 16.04 and 32 bit.
I have suspicions that there is a mandatory installation sequence and I do not follow this.

The error swig error: Unrecognized option -pthread has been fixed long ago - https://github.com/iamckn/airprobe/commits/master
Commits on May 13, 2011

Fix swig 'unrecognized option -pthread' compile error
GNURADIO_CORE_CFLAGS may set '-pthread' which is not parseable by swig,
so we need to explicitly use GNURADIO_CORE_INCLUDEDIR instead.

Also, the GNURADIO_CORE_INCLUDEDIR / swig directory needs to be explicitly
specified in Makefile.common

$ (GNURADIO_CORE_CFLAGS) \ change -I $ (GNURADIO_CORE_INCLUDEDIR) \
 -I $ (GNURADIO_CORE_INCLUDEDIR) / swig \

as well as
"The new version 3.7 GNU Radio is not compatible with AirProbe. You will need to install GNU Radio 3.6. However, neeo from the comments section of this post has created a patch which makes AirProbe compatible with GNU Radio 3.7."
 But airprobe is already with the patch. And in particular the lines

-I $ (GNURADIO_CORE_INCLUDEDIR) \
-I $ (GNURADIO_CORE_INCLUDEDIR) / swig \

fixed on

-I $ (GNURADIO_RUNTIME_INCLUDEDIR) \
-I $ (GNURADIO_RUNTIME_INCLUDEDIR) / swig \

**Comment by ghost** [comment]
thanks for your reply

**Comment by ghost** [comment]
Sorry in the first example, I did not copy from the terminal, here is the correct option

vic @ vic: ~ / airprobe / gsm-receiver / src / lib $ libtool --tag = CXX --mode = compile g ++ -DHAVE_CONFIG_H -I. -I ../ .. -g -O1 -Wno-strict-aliasing -Wno-parentheses -g -O2 -Wall -Woverloaded-virtual -MT _gsm_la-gsm.lo -MD -MP -MF .deps / _gsm_la-gsm .Tpo -c -o _gsm_la-gsm.lo `test -f 'gsm.cc' || echo './'`gsm.cc
libtool: compile: g ++ -DHAVE_CONFIG_H -I. -I ../ .. -g -O1 -Wno-strict-aliasing -Wno-parentheses -g -O2 -Wall -Woverloaded-virtual -MT _gsm_la-gsm.lo -MD -MP -MF .deps / _gsm_la-gsm .Tpo -c ./gsm.cc -fPIC -DPIC -o .libs / _gsm_la-gsm.o
g ++: error: ./gsm.cc: No such file or directory
g ++: fatal error: no input files
compilation terminated.
vic @ vic: ~ / airprobe / gsm-receiver / src / lib $

but I think the key error is - swig error: Unrecognized option -pthread as a result, the gsm.cc file is not created and as a result we get the error - g ++: error: ./gsm.cc: No such file or directory

**Comment by pcabreracamara** [comment]
Hi Victor,

Please, clean your airprobe gsm-receiver make files (`make clean`) and before trying again, check first:

- All GNU Radio requirements are met: [https://wiki.gnuradio.org/index.php/UbuntuInstall#Xenial_Xerus_.2816.04.29](url)

- Pthread is installed:
`apt install libpthread-stubs0-dev`

- Swig is install and not outdated version:
`swig -version` (apt install swig3.0)

Once you've checked everything, go ahead with a clean environment and `make`.

Regards,
Pedro

**Comment by pcabreracamara** [comment]
Hi Victor,

I have had to install this airprobe again on an Ubuntu 18 (GnuRadio 3.7.x) and I have noticed the following, I hope this will help you:

- Executing swig command by hand shows the error you commented:
```
swig error : Unrecognized option -pthread
```

- Once removed the unrecognized option from the command line, may arise unknown files errors. Solve these files location issues and finally swig will generate the files:
```
# swig -c++ -fvirtual -python -modern -keyword -w511 -outdir . -I -I -I/usr/local/include/ -I    -MD -MF .deps/gsm.Std -module gsm -o gsm.cc gsm.i
gsm.i:26: Error: Unable to find 'gnuradio.i'
```

-Finally you will be able to continue with the g++ compilation (or resume make process):
```
# g++ -DHAVE_CONFIG_H -I. -I../.. -I -I -pthread -I/usr/local/include/ -I -I/usr/include/python2.7 -I/usr/local/include -g -O1 -Wno-strict-aliasing -Wno-parentheses -g -O2 -Wall -Woverloaded-virtual -MT _gsm_la-gsm.lo -MD -MP -MF .deps/_gsm_la-gsm.Tpo -c ./gsm.cc  -fPIC -DPIC -o .libs/_gsm_la-gsm.o
#
```

I'm looking forward to hearing from you.
Pedro

**Comment by ghost** [comment]
Pedro Hi!
Thanks for answering. So you, too, got an error first.
"Once removed the unrecognized option from the command line," - where and how can this be done - removed the unrecognized option?
I have a make command running, I do not start anything manually.

Pedro, you did not use similar programs from gr-gsm? There is a similar one called qa_burst_printer.py. But I couldn’t start it yet, now I’m still understanding it. I did not find a description as an example of its use anywhere.
