### ISSUE TITLE
how fix it?

### ISSUE THREAD

**Issue by jamme1020031** [pcabreracamara/airprobe#2]
make[5]: Nothing to be done for 'all-am'.
make[5]: Leaving directory '/home/kali/airprobe/gsm-receiver/src/lib/decoder'
make[4]: Leaving directory '/home/kali/airprobe/gsm-receiver/src/lib/decoder'
make[4]: Entering directory '/home/kali/airprobe/gsm-receiver/src/lib'
/bin/bash ../../libtool  --tag=CXX   --mode=compile g++ -DHAVE_CONFIG_H -I. -I../..  -I -I -I/usr/include -I/usr/include/gnuradio/swig -I/usr/include/ -I../../src/lib/decoder/openbtsstuff -I/usr/include/python2.7    -g -O1 -Wno-strict-aliasing -Wno-parentheses  -g -O2 -Wall -Woverloaded-virtual -MT _gsm_la-gsm.lo -MD -MP -MF .deps/_gsm_la-gsm.Tpo -c -o _gsm_la-gsm.lo `test -f 'gsm.cc' || echo './'`gsm.cc
libtool: compile:  g++ -DHAVE_CONFIG_H -I. -I../.. -I -I -I/usr/include -I/usr/include/gnuradio/swig -I/usr/include/ -I../../src/lib/decoder/openbtsstuff -I/usr/include/python2.7 -g -O1 -Wno-strict-aliasing -Wno-parentheses -g -O2 -Wall -Woverloaded-virtual -MT _gsm_la-gsm.lo -MD -MP -MF .deps/_gsm_la-gsm.Tpo -c gsm.cc  -fPIC -DPIC -o .libs/_gsm_la-gsm.o
gsm.cc:2842:10: fatal error: gnuradio_swig_bug_workaround.h: No such file or directory
 2842 | #include <gnuradio_swig_bug_workaround.h> // mandatory bug fix
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[4]: *** [Makefile:765: _gsm_la-gsm.lo] Error 1
make[4]: Leaving directory '/home/kali/airprobe/gsm-receiver/src/lib'
make[3]: *** [Makefile:890: all-recursive] Error 1
make[3]: Leaving directory '/home/kali/airprobe/gsm-receiver/src/lib'
make[2]: *** [Makefile:426: all-recursive] Error 1
make[2]: Leaving directory '/home/kali/airprobe/gsm-receiver/src'
make[1]: *** [Makefile:581: all-recursive] Error 1
make[1]: Leaving directory '/home/kali/airprobe/gsm-receiver'
make: *** [Makefile:489: all] Error 2

**Comment by pcabreracamara** [comment]
Please, check your GnuRadio installation and configuration:

**fatal error: gnuradio_swig_bug_workaround.h: No such file or directory**
