### ISSUE TITLE
Problem with file "gsm.cc"

### ISSUE THREAD

**Issue by ghost** [pcabreracamara/airprobe#5]
Hi ....

I hope you are doing well. I have a question about your project airprobe. Could you please help me to clarify a specific problem?
when compiling it does not find the file “gsm.cc” 

here is an excerpt:

libtool: compile: g++ -DHAVE_CONFIG_H -I. -I../.. -I -I -I -I/usr/include/ -pthread -I -I/usr/include/python3.12 -g -O1 -Wno-strict-aliasing -Wno-parentheses -g -O2 -Wall -Woverloaded-virtual -MT _gsm_la-gsm.lo -MD -MP -MF .deps/_gsm_la-gsm.Tpo -c ./gsm.cc -fPIC -DPIC -o .libs/_gsm_la-gsm.o
cc1plus: fatal error: ./gsm.cc: No such file or directory
compilation terminated.
make[1]: *** [Makefile:762: _gsm_la-gsm.lo] Error 1
make[1]: Directory “/home/cadmin/airprobe/gsm-receiver/src/lib” is exited
make: *** [Makefile:887: all-recursive] Error 1

Many thanks in advance!

**Comment by pcabreracamara** [comment]
Hi,

Likely if you look a few lines above, you will see an error related to “pthread”:

`swig error : Unrecognized option -pthread`

This is a classic error related to airprobe requirements.
[https://groups.google.com/g/gr-gsm/c/Q0paU8vUyYE/m/WQd7S6m4AAAJ?pli=1](https://groups.google.com/g/gr-gsm/c/Q0paU8vUyYE/m/WQd7S6m4AAAJ?pli=1)
Kind regards,
Pedro
